-- SoenensMedia Portaal — Fase 32b: content-strategie data voor Decaigny Selected Cars & Vans
-- Eenmalig, na sql/025_content_strategie.sql. Vereist dat de klant al bestaat
-- (Klanten-tab, exacte naam "Decaigny Selected Cars & Vans") — anders doet dit script niets.

do $$
declare
  v_client_id uuid;
begin
  select id into v_client_id from clients where naam ilike '%Decaigny%' limit 1;
  if v_client_id is null then
    raise notice 'Geen klant met "Decaigny" in de naam gevonden — maak deze eerst aan in de Klanten-tab.';
    return;
  end if;

  insert into content_strategie (client_id, sector, volume, doelen, doelgroepen, kernboodschap)
  values (v_client_id, 'Multimerk occasies, personen- en bestelwagens', '5 shorts per maand', ARRAY['naambekendheid', 'employer branding']::text[], ARRAY['Particulier 25-55 uit West-Vlaanderen die twijfelt of de garage te vertrouwen is', 'Zelfstandige of kleine KMO die snel een bestelwagen nodig heeft', 'Toekomstige werknemer: mecanicien, carrosserie, magazijn']::text[], 'Niet ''kijk onze auto''s'', maar ''kijk hoe streng wij zijn voor een auto bij jou op de oprit staat''.')
  on conflict (client_id) do update set sector = excluded.sector, volume = excluded.volume, doelen = excluded.doelen, doelgroepen = excluded.doelgroepen, kernboodschap = excluded.kernboodschap, updated_at = now();

  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Wat krijg je hier voor €X?', 'Maand 1', ARRAY['prater-vrij', 'stock', 'snel']::text[], 'Drie wagens in dezelfde prijsklasse, elk met twee tekstregels. De kijker kiest in de comments.', 'Vijftienduizend euro. Drie wagens. Welke pak jij?', '3 + 3×8 + 4 = 31 sec', 'Doorlopende glide langs de drie, reflectie over de lak', 0);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Raad de kilometerstand', 'Maand 1', ARRAY['prater-vrij', 'stock', 'snel']::text[], 'Aanwijzingen in beurten — exterieur, bekleding, pedalen — en dan de reveal. De kijker analyseert mee.', 'Hoeveel km denk je dat deze gereden heeft?', '3 + 3×6 + 3 + 4 + 4 = 32 sec', 'Slijtagemacro''s in strijklicht, open diafragma', 1);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Welke past bij jouw stiel?', 'Maand 1', ARRAY['prater-vrij', 'stock']::text[], 'Drie bestelwagens naast drie beroepen. Verkoop die niet als verkoop voelt, en het raakt hun B2B-kant.', 'Schilder, elektricien of tuinaannemer. Welke is voor jou?', '3 + 3×8 + 4 = 31 sec', 'Laag standpunt, wagen rijdt in kader, schuifdeur open', 2);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Blind gekozen', 'Maand 1', ARRAY['prater-vrij', 'stock', 'snel', 'los']::text[], 'Blind een sleutel uit de sleutelkast trekken. Die wagen krijgt de spotlight, wat het ook is. Toeval maakt het eerlijk.', 'Wat we vandaag tonen, beslist het lot.', '3 + 8 + 5×4 + 4 = 35 sec', 'Sleutelkast in tegenlicht, hand die tast, sleutel die zwaait', 3);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Wat rijden ze hier zelf?', 'Maand 1', ARRAY['prater-vrij', 'mensen']::text[], 'De privéwagens van het personeel, met wie erbij hoort. Employer branding zonder één gesproken woord.', 'De mecanicien die jouw wagen keurt, rijdt zelf hierin.', '3 + 5×5 + 5 = 33 sec', 'Golden hour, zachte boog om persoon en wagen', 4);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Goedkoopste vs. duurste', 'beschikbaar', ARRAY['prater-vrij', 'stock', 'snel']::text[], 'Laagste en hoogste prijs uit de stock, met exact dezelfde drie details van elk. Toont de breedte van het aanbod.', '€6.500 en €48.000. Allebei bij ons op de parking.', '3 + 9 + 9 + 5 + 3 = 29 sec', 'Identieke beweging op beide, in split screen gemonteerd', 5);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Deze was in 3 dagen weg', 'beschikbaar', ARRAY['prater-vrij', 'stock', 'snel']::text[], 'Twee wagens: één die meteen verkocht, één die er nog staat. Waarom? De kijker gaat zelf redeneren.', 'Deze stond drie dagen. Deze staat er al vier maanden.', '3 + 10 + 10 + 5 = 28 sec', 'Lege plek op de parking waar de eerste stond', 6);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Wat is er veranderd?', 'beschikbaar', ARRAY['prater-vrij', 'stock']::text[], 'Twee generaties van hetzelfde model naast elkaar, punt voor punt vergeleken. Nostalgie plus informatie.', 'Dezelfde wagen. Zeven jaar verschil.', '3 + 4×6 + 5 = 32 sec', 'Neus tegen neus, camera glijdt van oud naar nieuw', 7);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'De kofferbaktest', 'beschikbaar', ARRAY['prater-vrij', 'stock', 'snel']::text[], 'Hoeveel valiezen krijg je erin? Zelfde valiezen, drie wagens. Concreet en meetbaar.', 'Gezin van vier, één week weg. Welke redt het?', '3 + 3×8 + 5 = 32 sec', 'Vaste camera, kofferbak die volloopt in timelapse', 8);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Wat kost dat per maand?', 'beschikbaar', ARRAY['prater-vrij', 'stock']::text[], 'Vraagprijs omgerekend naar een maandbedrag over vier jaar. Maakt een grote som ineens klein en begrijpelijk.', '€18.900. Of anders bekeken: [X] euro per maand.', '3 + 3×7 + 5 = 29 sec', 'Cijfer dat aftelt over het beeld van de wagen', 9);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Het geluid van…', 'beschikbaar', ARRAY['prater-vrij', 'stock', 'snel', 'los']::text[], 'Drie motoren, drie deuren, drie startgeluiden. Puur audio, kijker raadt mee. Werkt uitzonderlijk goed met koptelefoon.', 'Alleen luisteren. Welke is de duurste?', '3 + 3×7 + 6 = 30 sec', 'Macro op uitlaat of dashboard terwijl de motor aanslaat', 10);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'De stock in 30 seconden', 'beschikbaar', ARRAY['prater-vrij', 'stock']::text[], 'Eén doorlopende beweging langs alle wagens, met een teller die oploopt. Toont schaal zonder er iets over te zeggen.', 'Alles wat er vandaag staat. Zonder te stoppen.', '3 + 24 doorlopend + 3 = 30 sec', 'De hele video is er één — gimbal of drone, geen snit', 11);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Welke haalt de winter?', 'beschikbaar', ARRAY['prater-vrij', 'stock']::text[], 'Seizoensgebonden: banden, vierwielaandrijving, verwarmde zetels. Elk jaar opnieuw bruikbaar.', 'Eerste vorst komt eraan. Deze drie staan klaar.', '3 + 3×7 + 5 = 29 sec', 'Vroege ochtend, damp, koud licht, bandenprofiel in macro', 12);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Zou jij hem zelf rijden?', 'beschikbaar', ARRAY['prater-vrij', 'stock', 'los']::text[], 'Een medewerker rangschikt vijf wagens uit de stock op wat hij zelf zou kiezen. Meningen, geen verkoop.', 'Hij mag er één mee naar huis. Welke?', '3 + 5×5 + 5 = 33 sec', 'Hij loopt langs de rij, camera volgt in één beweging', 13);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Van inruil tot showroom', 'beschikbaar', ARRAY['prater-vrij', 'werkplaats']::text[], 'Eén wagen van vuil binnengekomen tot klaar in de stock. Staat of valt met de match cut.', 'Zo kwam deze bij ons binnen.', '3 + 18 + 5 + 4 = 30 sec', 'Match cut op exact hetzelfde kader, muziek valt stil', 14);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Schade → weg', 'beschikbaar', ARRAY['prater-vrij', 'werkplaats']::text[], 'Carrosserie voor en na op één deuk of kras. Bevredigend om te zien en het bewijst een dienst die ze onderbenutten.', 'Denk jij dat dit nog te herstellen is?', '3 + 6 + 14 + 5 = 28 sec', 'Strijklicht over het paneel, voor en na identiek belicht', 15);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Tegen de klok', 'beschikbaar', ARRAY['prater-vrij', 'werkplaats', 'snel', 'los']::text[], 'Timer in beeld, één handeling zo snel mogelijk. Mensen die goed zijn in iets snel zien doen is altijd kijkbaar.', 'Vier minuten. Denk je dat je sneller bent?', '3 + 20 versneld + 5 = 28 sec', 'Vaste wide plus handmacro''s, in ritme gesneden', 16);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Het detail dat niemand ziet', 'beschikbaar', ARRAY['prater-vrij', 'werkplaats', 'snel']::text[], 'Eén handeling in macro en met eigen geluid: velg poetsen, stoomreiniger, lakcorrectie. Bijna ASMR.', 'Geluid aan.', '3 + 4×5 + 4 = 27 sec', 'Macro met ondiepe scherptediepte, apart opgenomen geluid', 17);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'De controle, stap voor stap', 'beschikbaar', ARRAY['prater-vrij', 'werkplaats']::text[], 'De checklist die elke occasie doorloopt, visueel afgevinkt zonder dat iemand zegt hoe streng ze zijn.', 'Punt 1 van [X].', '3 + 6×4 + 5 = 32 sec', 'Wagen op de lift van onder, zaklamp die meebeweegt', 18);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Van transport tot oprit', 'beschikbaar', ARRAY['prater-vrij', 'stock']::text[], 'De volledige weg die een wagen aflegt vóór hij verkocht wordt: aankomst, controle, poets, stock. Montagevideo.', 'Vier weken geleden stond deze nog in Duitsland.', '3 + 4×6 + 5 = 32 sec', 'Wagen die van de oplegger rolt, laag standpunt', 19);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Handen', 'beschikbaar', ARRAY['prater-vrij', 'mensen']::text[], 'Portret van elke medewerker via zijn handen, met naam en jaren in dienst. Geen gezichten nodig, geen woorden.', 'Zeventien jaar. Elf jaar. Drie maanden.', '3 + 6×4 + 4 = 31 sec', 'Macro op handen in zijlicht, zwarte achtergrond', 20);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Je eerste auto', 'beschikbaar', ARRAY['mensen', 'los']::text[], 'Elke medewerker vertelt in vijftien seconden over zijn eerste wagen. Hier praat iedereen graag over — ook wie niet voor de camera wil.', 'Opel Kadett, 1994. En hij was er trots op.', '3 + 3×9 + 4 = 34 sec', 'Vaste opstelling, korte brandpuntsafstand, zachte achtergrond', 21);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Wat vinden we in inruilwagens', 'beschikbaar', ARRAY['mensen', 'los', 'snel']::text[], 'Een maand lang de rariteiten verzamelen die klanten achterlaten. Nul acteerwerk, altijd grappig.', 'Dit lag allemaal in wagens die klanten binnenbrachten.', '3 + 8×3 + 4 = 31 sec', 'Alles uitgestald op een werkbank, top-down, hard licht', 22);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Welke motor is dit?', 'beschikbaar', ARRAY['los', 'mensen']::text[], 'Blinde geluidsquiz voor de mecaniciens. Spel én bewijs van vakmanschap, zonder dat iemand het over vakmanschap heeft.', 'Onze mecanicien beweert dat hij dit hoort.', '3 + 3×8 + 5 = 32 sec', 'Zijn gezicht in close-up terwijl hij luistert', 23);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Wat wij weigeren', 'Vanaf maand 3', ARRAY['werkplaats']::text[], 'Waarom een wagen de stock niet haalt. Sterkste vertrouwensformat dat bestaat — maar het vraagt lef van de klant.', 'Deze wagen hebben we geweigerd. Dit is waarom.', '3 + 4×7 + 5 = 36 sec', 'Zaklampbundel in het donker die op het defect stopt', 24);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'De vraag van deze week', 'Vanaf maand 3', ARRAY['mensen']::text[], 'Eén echte klantvraag, één kort antwoord. Bouwt autoriteit op zodra er iemand comfortabel voor de camera staat.', 'Iemand vroeg me gisteren: [vraag].', '3 + 20 + 5 = 28 sec', 'Werkplaats onscherp op de achtergrond, hij scherp vooraan', 25);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Herken je hem aan één detail?', 'beschikbaar', ARRAY['prater-vrij', 'stock', 'snel', 'los']::text[], 'Macro op een grille, achterlicht of dorpelstuk. De kijker raadt het model, de reveal komt op het einde. Nul opzet, oneindig te herhalen, en het trekt automatisch de autoliefhebbers aan die willen bewijzen dat ze het wisten.', 'Eén detail. Weet jij welke wagen dit is?', '3 + 3×7 + 4 + 4 = 32 sec', 'Extreme macro in strijklicht, zwarte achtergrond, trage focuspull', 26);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Blindtest: nieuw of tweedehands?', 'beschikbaar', ARRAY['prater-vrij', 'stock']::text[], 'Twee interieurs in macro naast elkaar. De kijker raadt welke er tachtigduizend kilometer op heeft. Ontkracht het grootste bezwaar tegen occasies zonder er één woord aan vuil te maken.', 'Eén van deze twee heeft 80.000 km gereden.', '3 + 4×6 + 4 + 4 = 35 sec', 'Identiek belichte macro''s van stoelnaad, pook en stuurleer', 27);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'De laatste van zijn soort', 'beschikbaar', ARRAY['prater-vrij', 'stock', 'snel']::text[], 'Een model dat niet meer gemaakt wordt, of de laatste diesel in de stock. Nostalgie en urgentie tegelijk, en het geeft een gewone wagen ineens een verhaal.', 'Deze bouwen ze niet meer. En dit is de laatste die wij hebben.', '3 + 4×6 + 5 = 32 sec', 'Trage cirkel rond de wagen bij laag licht, alsof het een afscheid is', 28);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'De sleutelkast, elke maand opnieuw', 'beschikbaar', ARRAY['prater-vrij', 'snel', 'traag']::text[], 'Eén vast beeld van de sleutelkast, elke maand identiek gefilmd. Na een half jaar heb je een reeks die zonder woorden toont hoe de stock ademt. Kost je twee minuten per shoot.', 'Zes maanden, dezelfde kast.', '3 + 6×4 + 5 = 32 sec, bruikbaar vanaf maand 6', 'Sleutelkast in tegenlicht, vaste hoogte en hoek — noteer je instellingen', 29);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'Wat staat er op de teller als hij weggaat?', 'beschikbaar', ARRAY['prater-vrij', 'stock', 'traag']::text[], 'De kilometerstand bij verkoop, en hetzelfde beeld wanneer diezelfde klant een jaar later terugkomt voor onderhoud. Een video die geen concurrent kan maken, omdat niemand anders het een jaar geleden gefilmd heeft.', 'Vorig jaar stond hier 94.312.', '3 + 8 + 8 + 8 + 5 = 32 sec', 'Teller die aanspringt in het donker, cijfers scherp, rest onscherp', 30);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'De acht uur die niemand ziet', 'beschikbaar', ARRAY['prater-vrij', 'snel', 'traag']::text[], 'Eén parkeerplaats, één vaste camera, een volledige werkdag in timelapse. Wagens komen en gaan, het licht draait, schaduwen schuiven. Toont drukte zonder dat er iets over drukte gezegd wordt.', 'Eén plek. Eén dag. Kijk mee.', '3 + 22 doorlopend + 5 = 30 sec', 'De timelapse zelf — hoog standpunt, geen enkele snit', 31);
  insert into content_ideeen (client_id, naam, status, tags, wat, hook, lengte, heroshot, volgorde) values
    (v_client_id, 'De proefritroute', 'beschikbaar', ARRAY['prater-vrij', 'stock']::text[], 'Hun vaste proefritroute in POV, versneld. Lokaal keihard herkenbaar — mensen uit Izegem zien hun eigen straten voorbijkomen, en dat is precies waarom ze blijven kijken.', 'Dit is de weg die elke wagen hier aflegt.', '3 + 20 versneld + 4 + 4 = 31 sec', 'Camera laag achter het stuur, zon die door de bomen flikkert', 32);

  insert into content_scripts (client_id, titel, meta, shots, regie) values
    (v_client_id, '01 · Wat krijg je hier voor €15.000?', 'Bereik ±35 sec prater optioneel blok D, 11u30', '[{"tijd": "0:00", "beeld": "De drie wagens samen in kader, camera glijdt langzaam zijwaarts", "tekst_in_beeld": "€15.000. Drie wagens. Welke pak jij?", "gesproken": "\"Vijftienduizend euro. Drie wagens. Welke pak jij?\""}, {"tijd": "0:04", "beeld": "Wagen 1 — vaste beweging, zelfde kader voor alle drie", "tekst_in_beeld": "[MERK MODEL] · [BOUWJAAR] [KM] km", "gesproken": null}, {"tijd": "0:08", "beeld": "Snijden naar het detail dat deze wagen verkoopt — velg, interieur, trekhaak", "tekst_in_beeld": "Waarom deze: [ÉÉN REDEN]", "gesproken": "\"Deze heeft [x]. Dat vind je zelden in deze prijsklasse.\""}, {"tijd": "0:12", "beeld": "Wagen 2 — exact dezelfde beweging herhalen", "tekst_in_beeld": "[MERK MODEL] · [BOUWJAAR] [KM] km Waarom deze: [ÉÉN REDEN]", "gesproken": null}, {"tijd": "0:20", "beeld": "Wagen 3 — exact dezelfde beweging herhalen", "tekst_in_beeld": "[MERK MODEL] · [BOUWJAAR] [KM] km Waarom deze: [ÉÉN REDEN]", "gesproken": null}, {"tijd": "0:28", "beeld": "Terug naar de drie samen, zelfde openingsbeeld — cirkel rond", "tekst_in_beeld": "1, 2 of 3? Zeg het hieronder.", "gesproken": "\"Eén, twee of drie? Ik ben benieuwd.\""}]'::jsonb, 'Regie. De kracht zit in de herhaling: identiek kader, identieke beweging, identiek tekstblok. Wijkt er één af, dan valt het ritme uit elkaar. Film de drie wagens vlak na elkaar zonder de camera te verzetten. CTA: comments — dit is een bereikvideo, niet verkopen.');
  insert into content_scripts (client_id, titel, meta, shots, regie) values
    (v_client_id, '02 · Van inruil tot showroom', 'Vertrouwen ±30 sec geen prater nodig blok B en F', '[{"tijd": "0:00", "beeld": "De vuile wagen, vaste totaalshot vanaf het merkteken", "tekst_in_beeld": "Zo kwam deze bij ons binnen.", "gesproken": null}, {"tijd": "0:03", "beeld": "Drie snelle details van het vuil — velgen, dorpel, insecten op de neus", "tekst_in_beeld": "Geen tekst — laat de beelden werken", "gesproken": null}, {"tijd": "0:07", "beeld": "Interieur voor: matten, dashboard, bekerhouder", "tekst_in_beeld": "140.000 km aan sporen.", "gesproken": null}, {"tijd": "0:11", "beeld": "Poetsproces in ritme: schuim, borstel, hogedruk — slow motion, muziek zwelt", "tekst_in_beeld": "Geen tekst", "gesproken": null}, {"tijd": "0:20", "beeld": "Poetsmachine op de lak, macro, strijklicht", "tekst_in_beeld": "Elke wagen gaat hier door. Ook als niemand het ziet.", "gesproken": null}, {"tijd": "0:25", "beeld": "MATCH CUT naar de \"na\" — exact hetzelfde kader als 0:00, muziek valt stil", "tekst_in_beeld": "Zo staat hij nu in onze stock.", "gesproken": null}, {"tijd": "0:29", "beeld": "Laatste beeld: wagen glijdt de stock in of deur die dichtvalt", "tekst_in_beeld": "Decaigny Selected Cars · Izegem", "gesproken": null}]'::jsonb, 'Regie. Alles hangt aan de match cut op 0:25. Zelfde statiefhoogte, zelfde brandpunt, zelfde afstand — noteer je instellingen ''s ochtends. Laat de muziek stilvallen op het snijpunt: die ene seconde stilte is wat de video deelbaar maakt. CTA: geen. Deze video verkoopt door niets te vragen.');
  insert into content_scripts (client_id, titel, meta, shots, regie) values
    (v_client_id, '03 · Dag in het leven van een mecanicien', 'Employer branding ±55 sec prater sterk aanbevolen blok A en F', '[{"tijd": "0:00", "beeld": "Poort die opengaat, tegenlicht, silhouet van de medewerker", "tekst_in_beeld": "07:12", "gesproken": "\"07u12. De eerste wagen staat al te wachten.\""}, {"tijd": "0:05", "beeld": "Koffie, handen, jas uit, overall aan", "tekst_in_beeld": "07:30 — koffie, en dan beginnen", "gesproken": null}, {"tijd": "0:12", "beeld": "Eerste wagen op de brug, camera laag van onder omhoog", "tekst_in_beeld": "08:00 — wagen 1 van vandaag", "gesproken": "\"Meestal weet ik binnen twee minuten wat er scheelt.\""}, {"tijd": "0:20", "beeld": "Reeks handshots in ritme: sleutel, diagnosetoestel, vonken, olie", "tekst_in_beeld": "Geen tekst — tempo optrekken", "gesproken": null}, {"tijd": "0:30", "beeld": "Middag: even stil, boterhammen, collega die iets zegt en gelach", "tekst_in_beeld": "12:15", "gesproken": null}, {"tijd": "0:36", "beeld": "Namiddag, tempo terug omhoog — tweede reeks handshots", "tekst_in_beeld": "Vandaag: 7 wagens", "gesproken": null}, {"tijd": "0:44", "beeld": "Laatste wagen rijdt buiten, licht gaat uit, hij kijkt de werkplaats rond", "tekst_in_beeld": "17:45", "gesproken": "\"Waarom ik hier graag werk? Ik krijg de tijd om het deftig te doen.\""}, {"tijd": "0:52", "beeld": "Gevel bij laag licht, rustig eindbeeld", "tekst_in_beeld": "Wij zoeken versterking. Stuur ons een bericht.", "gesproken": null}]'::jsonb, 'Regie. Niets sturen tot 0:44. Laat hem werken en volg — hoe minder je vraagt, hoe echter het is. Die ene zin op het einde neem je apart op, aan het einde van de dag als hij je gewoon is. Vraag hem eerst gewoon waarom hij hier graag werkt, zonder camera, en film dan het antwoord dat hij spontaan gaf. CTA: dit is je enige meetbare video — hou bij hoeveel berichten er binnenkomen.');
  insert into content_scripts (client_id, titel, meta, shots, regie) values
    (v_client_id, '04 · Wat wij weigeren', 'Vertrouwen ±40 sec prater of voice-over blok C, 10u00', '[{"tijd": "0:00", "beeld": "Wagen op de lift, camera laag, zaklamp aan in het donker", "tekst_in_beeld": "Deze wagen hebben we geweigerd.", "gesproken": "\"Deze wagen hebben we geweigerd. Ik toon je waarom.\""}, {"tijd": "0:05", "beeld": "Zaklampbundel glijdt over de onderkant, stopt op het probleem", "tekst_in_beeld": null, "gesproken": "\"Van boven zag hij er perfect uit. Nette wagen, mooie kilometerstand.\""}, {"tijd": "0:12", "beeld": "Macro op het defect — roest, lek, slijtage. Twee à drie hoeken", "tekst_in_beeld": "Hier zit het probleem.", "gesproken": "\"Maar kijk hier. Dat krijg je niet meer weg.\""}, {"tijd": "0:20", "beeld": "Hand die het aanwijst of eraan voelt", "tekst_in_beeld": null, "gesproken": "\"Wij zouden dit kunnen verkopen. Iemand koopt dat wel.\""}, {"tijd": "0:27", "beeld": "Wagen komt naar beneden, licht gaat aan, ruimte wordt weer normaal", "tekst_in_beeld": null, "gesproken": "\"Maar dan staat die klant hier binnen het jaar terug. En dan is het onze naam die eraan hangt.\""}, {"tijd": "0:35", "beeld": "Wide van de stock — de wagens die het wél haalden", "tekst_in_beeld": "Van elke 10 wagens die binnenkomen, halen er [X] onze stock niet.", "gesproken": null}]'::jsonb, 'Regie. Donkerder graden dan de rest — dit mag documentair aanvoelen. Neem de audio hoe dan ook apart op met een lavalier of recorder, ook als hij in beeld praat: dan kan je in de montage nog kiezen tussen sync en voice-over. Vraag hem vooraf het echte cijfer voor het slotbeeld; een verzonnen cijfer voelt meteen als reclame. CTA: geen. De video ís de CTA.');
  insert into content_scripts (client_id, titel, meta, shots, regie) values
    (v_client_id, '05 · Past dit erin?', 'Bereik + bestelwagens ±30 sec geen prater nodig blok E, 13u00', '[{"tijd": "0:00", "beeld": "Het object staat naast de gesloten bestelwagen — beide volledig in kader", "tekst_in_beeld": "Past dit hierin?", "gesproken": "\"Een volledige keuken. Past dat hierin?\""}, {"tijd": "0:03", "beeld": "Deuren gaan open, lege laadruimte, camera blijft staan", "tekst_in_beeld": "[MODEL] · [X] m³", "gesproken": null}, {"tijd": "0:07", "beeld": "Meetlint tegen de laadvloer, cijfer in beeld", "tekst_in_beeld": "[X] cm lang · [X] cm breed", "gesproken": null}, {"tijd": "0:11", "beeld": "Inladen in timelapse — camera niet verplaatsen, dat is de hele grap", "tekst_in_beeld": "Geen tekst", "gesproken": null}, {"tijd": "0:22", "beeld": "Laatste stuk erin, iemand duwt de deur dicht — reveal", "tekst_in_beeld": "Past.", "gesproken": null}, {"tijd": "0:26", "beeld": "Wagen rijdt weg of staat rustig in beeld", "tekst_in_beeld": "[X] bestelwagens in stock. Izegem & Ardooie.", "gesproken": null}]'::jsonb, 'Regie. Statief, één hoek, niet verzetten — het effect komt van de onveranderde compositie waarin de wagen volloopt. Kies iets dat er écht niet in lijkt te passen, anders is er geen spanning. Als het uiteindelijk níét past: nog beter, publiceer dat gewoon. CTA: voorraad noemen, niet aanprijzen.');

  insert into content_hookformules (client_id, categorie, waarom, voorbeelden, volgorde) values
    (v_client_id, 'Getal', 'Belooft een afgebakende inhoud. Werkt omdat de kijker weet hoelang het duurt.', ARRAY['3 dingen die je moet checken vóór je een tweedehands koopt', 'De 3 fouten die iedereen maakt met een inruil', '€15.000 . Drie opties. Welke pak jij?', '40 controles vóór wij een wagen durven verkopen']::text[], 0);
  insert into content_hookformules (client_id, categorie, waarom, voorbeelden, volgorde) values
    (v_client_id, 'Weigering', 'Je sterkste vertrouwenshaak. Zeggen wat je niet doet is geloofwaardiger dan zeggen wat je wel doet.', ARRAY['Deze wagen hebben we geweigerd. Dit is waarom.', 'Wij verkopen dit niet. Zelfs niet met korting.', 'Van de 10 wagens die binnenkomen, halen er 4 onze stock niet', 'Als je dit ziet bij een garage: wegblijven']::text[], 1);
  insert into content_hookformules (client_id, categorie, waarom, voorbeelden, volgorde) values
    (v_client_id, 'Tijd', 'Een tijdstip of tijdsduur maakt het concreet en zet de kijker in het moment.', ARRAY['07u12 . De eerste wagen staat al te wachten.', 'Dit duurt 4 minuten . Onze snelste doet het in 2 .', 'Zes uur later ziet dezelfde wagen er zo uit', 'Twee jaar geleden stond hij hier als stagiair']::text[], 2);
  insert into content_hookformules (client_id, categorie, waarom, voorbeelden, volgorde) values
    (v_client_id, 'Contrast', 'Twee beelden naast elkaar. Werkt zonder woorden, dus perfect als niemand voor de camera wil.', ARRAY['Zo zag deze eruit toen hij binnenkwam', 'Zelfde budget. Links of rechts?', 'Denk jij dat dit nog te herstellen is?', 'Iedereen zegt veel km = slechte wagen . Klopt niet.']::text[], 3);
  insert into content_hookformules (client_id, categorie, waarom, voorbeelden, volgorde) values
    (v_client_id, 'Vraag uit de praktijk', 'Laat de klant zelf de vraag stellen. Herkenning is de snelste manier om iemand te doen blijven kijken.', ARRAY['Elke week krijgen we deze vraag: …', 'Een klant vroeg me gisteren: …', 'Mag ik eerlijk zijn over garantie ?', 'Dit vraagt niemand, maar het zou wel moeten']::text[], 4);
  insert into content_hookformules (client_id, categorie, waarom, voorbeelden, volgorde) values
    (v_client_id, 'Test', 'Een openstaande uitkomst. De kijker blijft omdat hij het antwoord wil zien.', ARRAY['Een volledige keuken . Past dat hierin?', 'Hoeveel fietsen krijgen we hierin? Gok eens.', 'Wij testen het, zodat jij het niet moet doen', 'Dit gaat waarschijnlijk mislukken']::text[], 5);

  insert into content_draaidag (client_id, tijd, blok, titel, waarom, shots, volgorde) values
    (v_client_id, '07:00', 'A', 'Dag in het leven — ochtend Short 3', 'Je moet er zijn wanneer zij beginnen. Ochtendlicht door de poort is je beste licht van de dag.', ARRAY['Aankomst medewerker, van achter gevolgd', 'Poort of rolluik dat opengaat, tegenlicht', 'Koffie, handen, eerste woorden van de dag', 'Eerste wagen die binnenrijdt of op de brug gaat', 'Wide van de werkplaats die op gang komt', 'Tijdstempel-referentie: klok, uurwerk of telefoon']::text[], 0);
  insert into content_draaidag (client_id, tijd, blok, titel, waarom, shots, volgorde) values
    (v_client_id, '08:30', 'B', 'Inruilwagen — de "voor" Short 2', 'Kritiek blok. Zonder vuile wagen is er geen transformatie. Zet een merkteken op de grond zodat je hem vanmiddag exact terugplaatst.', ARRAY['Merkteken op de grond leggen + hoek noteren', '"Voor" — vaste totaalshot, statief, exacte hoek', 'Detail vuil: velgen, dorpels, insecten op de neus', 'Interieur voor: matten, dashboard, bekerhouder', 'Wagen die de poetsplaats binnenrijdt', 'Poetsproces: schuim, borstel, hogedruk, slow motion']::text[], 1);
  insert into content_draaidag (client_id, tijd, blok, titel, waarom, shots, volgorde) values
    (v_client_id, '10:00', 'C', 'Wat wij weigeren + werkplaats Short 4', 'Zelfde locatie en lichtsetup als blok B. Donker en documentair — dit mag er anders uitzien dan de rest.', ARRAY['Wagen op de lift, camera laag, van onder omhoog', 'Zaklamp die het probleem uitlicht (roest, lek, slijtage)', 'Macro op het defect, 2 à 3 verschillende', 'Hand die aanwijst of eraan voelt', 'Uitleg op camera of losse audio voor voice-over', 'Slotbeeld: wagen die terug naar beneden komt']::text[], 2);
  insert into content_draaidag (client_id, tijd, blok, titel, waarom, shots, volgorde) values
    (v_client_id, '11:30', 'D', 'Drie wagens in één prijsklasse Short 1', 'Hoge zon = harde schaduw. Werk aan de schaduwzijde van het gebouw of onder de luifel.', ARRAY['Wagen 1 — identieke beweging en kader', 'Wagen 2 — identieke beweging en kader', 'Wagen 3 — identieke beweging en kader', 'Per wagen: km-stand op de teller, close-up', 'Per wagen: één detail dat hem verkoopt', 'Openingsbeeld: de drie samen in kader']::text[], 3);
  insert into content_draaidag (client_id, tijd, blok, titel, waarom, shots, volgorde) values
    (v_client_id, '13:00', 'E', 'Past dit erin? Short 5', 'Losstaand blok, weinig afhankelijk van licht. Perfect voor het dipmoment na de middag.', ARRAY['Lege laadruimte, vaste camera achteraan', 'Het object buiten de wagen, naast elkaar ter vergelijking', 'Inladen in timelapse, camera niet verplaatsen', 'Reveal: deuren die dichtgaan', 'Meetlint of maten in beeld voor geloofwaardigheid']::text[], 4);
  insert into content_draaidag (client_id, tijd, blok, titel, waarom, shots, volgorde) values
    (v_client_id, '14:00', 'F', 'De "na" + restant dag in het leven Short 2 + 3', 'De wagen is intussen gepoetst. Daarom moest blok B vroeg. Blijf 20 minuten langer voor gevelbeelden bij laag licht.', ARRAY['"Na" — exact dezelfde hoek als blok B, match cut', 'Detail na: velg, lak, interieur — zelfde kaders', 'Wagen die de stock in rijdt of geparkeerd wordt', 'Einde werkdag: laatste wagen buiten, licht uit', 'Gevel en toonzaal bij laag licht', 'Stock-overzicht van hoog standpunt of drone']::text[], 5);

  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Handen aan gereedschap, macro — minimum 10 varianten', 0);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Sleutel die aangedraaid wordt, geluid mee opnemen', 1);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Vonken bij lassen of slijpen, tegenlicht', 2);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Poetsmachine op lak, slow motion', 3);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Handen die vuil zijn, in detail', 4);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Meetinstrument of diagnosetoestel in gebruik', 5);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Wagen die op de lift gaat, camera laag', 6);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Wielen die draaien tijdens het binnenrijden', 7);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Deur die opengaat, van binnenuit gefilmd', 8);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Km-teller die aanspringt', 9);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Reflectie over de lak, camera glijdend', 10);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Stock-overzicht van hoog standpunt of drone', 11);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Elk gezicht in het bedrijf, 5 seconden neutraal', 12);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Iemand die lacht of iets uitlegt aan een collega', 13);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Sleutelbord, sleutels die genomen worden', 14);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Sleuteloverhandiging aan een klant', 15);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Gevel en toonzaal bij laag licht', 16);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Logo of naam in beeld, ondiepe scherptediepte', 17);
  insert into content_broll (client_id, tekst, volgorde) values (v_client_id, 'Werkplaats leeg aan het einde van de dag', 18);

end $$;
